In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [6]:
type(df['Name'])

pandas.core.series.Series

In [7]:
df[['Name','Embarked','Ticket']]

,Name,Embarked,Ticket
0,"Braund, Mr. Owen Harris",S,A/5 21171
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",C,PC 17599
2,"Heikkinen, Miss. Laina",S,STON/O2. 3101282
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",S,113803
4,"Allen, Mr. William Henry",S,373450
...,...,...,...
886,"Montvila, Rev. Juozas",S,211536
887,"Graham, Miss. Margaret Edith",S,112053
888,"Johnston, Miss. Catherine Helen ""Carrie""",S,W./C. 6607
889,"Behr, Mr. Karl Howell",C,111369
890,"Dooley, Mr. Patrick",Q,370376

In [8]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
df.iloc[777]

PassengerId                              778
Survived                                   1
Pclass                                     3
Name           Emanuel, Miss. Virginia Ethel
Sex                                   female
Age                                      5.0
SibSp                                      0
Parch                                      0
Ticket                                364516
Fare                                  12.475
Cabin                                    NaN
Embarked                                   S
Name: 777, dtype: object

In [10]:
df.iloc[[36,536,353,678,244]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
536,537,0,1,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S
353,354,0,3,"Arnold-Franchi, Mr. Josef",male,25.0,1,0,349237,17.8000,NaN,S
678,679,0,3,"Goodwin, Mrs. Frederick (Augusta Tyler)",female,43.0,1,6,CA 2144,46.9000,NaN,S
244,245,0,3,"Attalah, Mr. Sleiman",male,30.0,0,0,2694,7.2250,NaN,C

In [11]:
df.iloc[[0,1,2],3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
Name: Name, dtype: object

In [12]:
df.iloc[0,[1,2,3]]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Name: 0, dtype: object

In [13]:
df.loc[689]

PassengerId                                  690
Survived                                       1
Pclass                                         1
Name           Madill, Miss. Georgette Alexandra
Sex                                       female
Age                                         15.0
SibSp                                          0
Parch                                          1
Ticket                                     24160
Fare                                    211.3375
Cabin                                         B5
Embarked                                       S
Name: 689, dtype: object

In [14]:
df.loc[[787,689],'Name']

787            Rice, Master. George Hugh
689    Madill, Miss. Georgette Alexandra
Name: Name, dtype: object

In [15]:
df.loc[[787,689],['Embarked','Name']]

    Embarked                               Name
787        Q          Rice, Master. George Hugh
689        S  Madill, Miss. Georgette Alexandra

In [16]:
df.shape

(891, 12)

In [17]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [18]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [19]:
df.loc[0:25,'Name']

0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
11                             Bonnell, Miss. Elizabeth
12                       Saundercock, Mr. William Henry
13                          Andersson, Mr. Anders Johan
14                 Vestrom, Miss. Hulda Amanda Adolfina
15                     Hewlett, Mrs. (Mary D Kingcome)
16                                 Rice, Master. Eugene
17                         Williams, Mr. Charles Eugene
18    Vander Planke, Mrs. Julius (Emelia Maria Vande...
19                              Masselmani, Mrs. Fatima
20                                 Fynney, Mr. Joseph J
21                                Beesley, Mr. Lawrence
22                          McGowan, Miss. Anna "Annie"
23                         Sloper, Mr. William Thompson
24                        Palsson, Miss. Torborg Danira
25    Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
Name: Name, dtype: object

In [20]:
df.loc[0:20,'PassengerId':'Age']

,PassengerId,Survived,Pclass,Name,Sex,Age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0
5,6,0,3,"Moran, Mr. James",male,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0
16,17,0,3,"Rice, Master. Eugene",male,2.0
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0