In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('test.csv')

In [4]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [7]:
df['Age_Group'] = pd.cut(df['Age'], bins=[0, 12, 18, 35, 60, 100])

In [8]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,"(18, 35]"
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,"(35, 60]"
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,"(60, 100]"
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,"(18, 35]"
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,"(18, 35]"

In [9]:
df['Age_Group'] = pd.cut(df['Age'], bins=[0, 12, 18, 35, 60, 100], labels=['Child', 'Teen', 'Young Adult', 'Adult', 'Senior'])

In [10]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Young Adult
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Adult
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Senior
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Young Adult
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Young Adult

In [13]:
df['Fare_Bin'] = pd.qcut(df['Fare'], q=4)

In [14]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group,Fare_Bin
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Young Adult,"(-0.001, 7.896]"
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Adult,"(-0.001, 7.896]"
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Senior,"(7.896, 14.454]"
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Young Adult,"(7.896, 14.454]"
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Young Adult,"(7.896, 14.454]"

In [15]:
df['Fare_Bin'] = pd.qcut(df['Fare'], q=4, labels=['Low', 'Medium', 'High', 'Very High'])

In [16]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group,Fare_Bin
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Young Adult,Low
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Adult,Low
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Senior,Medium
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Young Adult,Medium
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Young Adult,Medium

In [17]:
df.Age_Group.value_counts()

Age_Group
Young Adult    173
Adult           94
Teen            29
Child           25
Senior          11
Name: count, dtype: int64

In [18]:
df.Fare_Bin.value_counts()

Fare_Bin
Low          114
High         105
Very High    102
Medium        96
Name: count, dtype: int64

In [21]:
Fare_grp= df.groupby(['Fare'],as_index = False).agg(totalFare=('Fare','sum')).sort_values(by='totalFare',ascending=False,ignore_index=True)

In [23]:
Fare_grp.head(20)

        Fare  totalFare
0   262.3750  1311.8750
1   211.5000   846.0000
2   221.7792   665.3376
3   263.0000   526.0000
4   512.3292   512.3292
5    26.0000   494.0000
6   134.5000   403.5000
7   164.8667   329.7334
8   151.5500   303.1000
9    69.5500   278.2000
10  136.7792   273.5584
11   83.1583   249.4749
12  247.5208   247.5208
13  227.5250   227.5250
14   13.0000   221.0000
15  211.3375   211.3375
16   65.0000   195.0000
17   93.5000   187.0000
18   26.5500   185.8500
19   59.4000   178.2000

In [24]:
pd.cut(Fare_grp['totalFare'],right=False,bins=10)

0      [1180.688, 1313.187)
1        [787.125, 918.312)
2        [655.938, 787.125)
3         [524.75, 655.938)
4         [393.562, 524.75)
               ...
164          [0.0, 131.188)
165          [0.0, 131.188)
166          [0.0, 131.188)
167          [0.0, 131.188)
168          [0.0, 131.188)
Name: totalFare, Length: 169, dtype: category
Categories (10, interval[float64, left]): [[0.0, 131.188) < [131.188, 262.375) < [262.375, 393.562) < [393.562, 524.75) ... [787.125, 918.312) < [918.312, 1049.5) < [1049.5, 1180.688) < [1180.688, 1313.187)]

In [26]:
pd.qcut(Fare_grp['totalFare'], q=5, duplicates = 'drop', precision=2)

0      (116.1, 1311.88]
1      (116.1, 1311.88]
2      (116.1, 1311.88]
3      (116.1, 1311.88]
4      (116.1, 1311.88]
             ...
164      (-0.01, 14.43]
165      (-0.01, 14.43]
166      (-0.01, 14.43]
167      (-0.01, 14.43]
168      (-0.01, 14.43]
Name: totalFare, Length: 169, dtype: category
Categories (5, interval[float64, right]): [(-0.01, 14.43] < (14.43, 29.02] < (29.02, 51.28] < (51.28, 116.1] < (116.1, 1311.88]]