In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('test.csv')

In [4]:
df.head(20)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S
10,902,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S
11,903,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,NaN,S
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
13,905,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
16,908,2,"Keane, Mr. Daniel",male,35.0,0,0,233734,12.3500,NaN,Q
17,909,3,"Assaf, Mr. Gerios",male,21.0,0,0,2692,7.2250,NaN,C
18,910,3,"Ilmakangas, Miss. Ida Livija",female,27.0,1,0,STON/O2. 3101270,7.9250,NaN,S
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C

In [5]:
df.sort_values(by = 'Name')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
392,1284,3,"Abbott, Master. Eugene Joseph",male,13.0,0,2,C.A. 2673,20.2500,NaN,S
345,1237,3,"Abelseth, Miss. Karen Marie",female,16.0,0,0,348125,7.6500,NaN,S
57,949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,0,348122,7.6500,F G63,S
251,1143,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,0,SOTON/O2 3101284,7.9250,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
336,1228,2,"de Brito, Mr. Jose Joaquim",male,32.0,0,0,244360,13.0000,NaN,S
260,1152,3,"de Messemaeker, Mr. Guillaume Joseph",male,36.5,1,0,345572,17.4000,NaN,S
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
344,1236,3,"van Billiard, Master. James William",male,NaN,1,1,A/5. 851,14.5000,NaN,S
192,1084,3,"van Billiard, Master. Walter John",male,11.5,1,1,A/5. 851,14.5000,NaN,S

In [6]:
df.sort_values(by = 'Name',ascending = False)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
192,1084,3,"van Billiard, Master. Walter John",male,11.5,1,1,A/5. 851,14.5000,NaN,S
344,1236,3,"van Billiard, Master. James William",male,NaN,1,1,A/5. 851,14.5000,NaN,S
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
260,1152,3,"de Messemaeker, Mr. Guillaume Joseph",male,36.5,1,0,345572,17.4000,NaN,S
336,1228,2,"de Brito, Mr. Jose Joaquim",male,32.0,0,0,244360,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
251,1143,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,0,SOTON/O2 3101284,7.9250,NaN,S
57,949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,0,348122,7.6500,F G63,S
345,1237,3,"Abelseth, Miss. Karen Marie",female,16.0,0,0,348125,7.6500,NaN,S
392,1284,3,"Abbott, Master. Eugene Joseph",male,13.0,0,2,C.A. 2673,20.2500,NaN,S

In [10]:
df.sort_values(by = ['Name','Age'],ascending = True).head(50)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
392,1284,3,"Abbott, Master. Eugene Joseph",male,13.00,0,2,C.A. 2673,20.2500,NaN,S
345,1237,3,"Abelseth, Miss. Karen Marie",female,16.00,0,0,348125,7.6500,NaN,S
57,949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.00,0,0,348122,7.6500,F G63,S
251,1143,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.00,0,0,SOTON/O2 3101284,7.9250,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00,0,0,2657,7.2292,NaN,C
307,1199,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S
78,970,2,"Aldworth, Mr. Charles Augustus",male,30.00,0,0,248744,13.0000,NaN,S
306,1198,1,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
210,1102,3,"Andersen, Mr. Albert Karvin",male,32.00,0,0,C 4001,22.5250,NaN,S
214,1106,3,"Andersson, Miss. Ida Augusta Margareta",female,38.00,4,2,347091,7.7750,NaN,S
320,1212,3,"Andersson, Mr. Johan Samuel",male,26.00,0,0,347075,7.7750,NaN,S
204,1096,2,"Andrew, Mr. Frank Thomas",male,25.00,0,0,C.A. 34050,10.5000,NaN,S
295,1187,3,"Angheloff, Mr. Minko",male,26.00,0,0,349202,7.8958,NaN,S
190,1082,2,"Angle, Mr. William A",male,34.00,1,0,226875,26.0000,NaN,S
386,1278,3,"Aronsson, Mr. Ernst Axel Algot",male,24.00,0,0,349911,7.7750,NaN,S
387,1279,2,"Ashby, Mr. John",male,57.00,0,0,244346,13.0000,NaN,S
379,1271,3,"Asplund, Master. Carl Edgar",male,5.00,4,2,347077,31.3875,NaN,S
154,1046,3,"Asplund, Master. Filip Oscar",male,13.00,4,2,347077,31.3875,NaN,S
174,1066,3,"Asplund, Mr. Carl Oscar Vilhelm Gustafsson",male,40.00,1,5,347077,31.3875,NaN,S
226,1118,3,"Asplund, Mr. Johan Charles",male,23.00,0,0,350054,7.7958,NaN,S
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.00,0,0,2696,7.2250,NaN,C
17,909,3,"Assaf, Mr. Gerios",male,21.00,0,0,2692,7.2250,NaN,C
325,1217,3,"Assam, Mr. Ali",male,23.00,0,0,SOTON/O.Q. 3101309,7.0500,NaN,S
202,1094,1,"Astor, Col. John Jacob",male,47.00,1,0,PC 17757,227.5250,C62 C64,C
237,1129,3,"Baccos, Mr. Raffull",male,20.00,0,0,2679,7.2250,NaN,C
87,979,3,"Badman, Miss. Emily Louisa",female,18.00,0,0,A/4 31416,8.0500,NaN,S
198,1090,2,"Baimbrigge, Mr. Charles Robert",male,23.00,0,0,C.A. 31030,10.5000,NaN,S
86,978,3,"Barry, Miss. Julia",female,27.00,0,0,330844,7.8792,NaN,Q
118,1010,1,"Beattie, Mr. Thomson",male,36.00,0,0,13050,75.2417,C6,C
143,1035,2,"Beauchamp, Mr. Henry James",male,28.00,0,0,244358,26.0000,NaN,S
326,1218,2,"Becker, Miss. Ruth Elizabeth",female,12.00,2,1,230136,39.0000,F4,S
178,1070,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.00,0,3,230136,39.0000,F4,S
258,1150,2,"Bentham, Miss. Lilian W",female,19.00,0,0,28404,13.0000,NaN,S
339,1231,3,"Betros, Master. Seman",male,NaN,0,0,2622,7.2292,NaN,C
156,1048,1,"Bird, Miss. Ellen",female,29.00,0,0,PC 17483,221.7792,C97,S
94,986,1,"Birnbaum, Mr. Jakob",male,25.00,0,0,13905,26.0000,NaN,C
62,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.00,0,0,347090,7.7500,NaN,S
400,1292,1,"Bonnell, Miss. Caroline",female,30.00,0,0,36928,164.8667,C7,S
158,1050,1,"Borebank, Mr. John James",male,42.00,0,0,110489,26.5500,D22,S
346,1238,2,"Botsford, Mr. William Hull",male,26.00,0,0,237670,13.0000,NaN,S
80,972,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,NaN,C
375,1267,1,"Bowen, Miss. Grace Scott",female,45.00,0,0,PC 17608,262.3750,NaN,C
128,1020,2,"Bowenur, Mr. Solomon",male,42.00,0,0,211535,13.0000,NaN,S
63,955,3,"Bradley, Miss. Bridget Delia",female,22.00,0,0,334914,7.7250,NaN,Q
28,920,1,"Brady, Mr. John Bertram",male,41.00,0,0,113054,30.5000,A21,S
98,990,3,"Braf, Miss. Elin Ester Maria",female,20.00,0,0,347471,7.8542,NaN,S
166,1058,1,"Brandeis, Mr. Emil",male,48.00,0,0,PC 17591,50.4958,B10,C
126,1018,3,"Brobeck, Mr. Karl Rudolf",male,22.00,0,0,350045,7.7958,NaN,S
175,1067,2,"Brown, Miss. Edith Eileen",female,15.00,0,2,29750,39.0000,NaN,S
356,1248,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.00,2,0,11769,51.4792,C101,S

In [12]:
df.sort_values(by = ['Name','Age'],ascending = [False,True]).head(50)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
192,1084,3,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.5000,NaN,S
344,1236,3,"van Billiard, Master. James William",male,NaN,1,1,A/5. 851,14.5000,NaN,S
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.00,1,0,SC/PARIS 2167,27.7208,NaN,C
260,1152,3,"de Messemaeker, Mr. Guillaume Joseph",male,36.50,1,0,345572,17.4000,NaN,S
336,1228,2,"de Brito, Mr. Jose Joaquim",male,32.00,0,0,244360,13.0000,NaN,S
171,1063,3,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C
136,1028,3,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C
162,1054,2,"Wright, Miss. Marion",female,26.00,0,0,220844,13.5000,NaN,S
294,1186,3,"Wittevrongel, Mr. Camille",male,36.00,0,0,345771,9.5000,NaN,S
3,895,3,"Wirz, Mr. Albert",male,27.00,0,0,315154,8.6625,NaN,S
371,1263,1,"Wilson, Miss. Helen Alice",female,31.00,0,0,16966,134.5000,E39 E41,C
23,915,1,"Williams, Mr. Richard Norris II",male,21.00,0,1,PC 17597,61.3792,NaN,C
108,1000,3,"Willer, Mr. Aaron (Abi Weller"")""",male,NaN,0,0,3410,8.7125,NaN,S
231,1123,1,"Willard, Miss. Constance",female,21.00,0,0,113795,26.5500,NaN,S
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00,1,0,363272,7.0000,NaN,S
232,1124,3,"Wiklund, Mr. Karl Johan",male,21.00,1,0,3101266,6.4958,NaN,S
218,1110,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.00,1,1,113503,211.5000,C80,C
407,1299,1,"Widener, Mr. George Dunton",male,50.00,1,1,113503,211.5000,C80,C
217,1109,1,"Wick, Mr. George Dennick",male,57.00,1,1,36928,164.8667,NaN,S
314,1206,1,"White, Mrs. John Stuart (Ella Holmes)",female,55.00,0,0,PC 17760,135.6333,C32,C
384,1276,2,"Wheeler, Mr. Edwin Frederick""""",male,NaN,0,0,SC/PARIS 2159,12.8750,NaN,S
347,1239,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.00,0,0,2688,7.2292,NaN,C
250,1142,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S
254,1146,3,"Wenzel, Mr. Linhart",male,32.50,0,0,345775,9.5000,NaN,S
262,1154,2,"Wells, Mrs. Arthur Henry (Addie"" Dart Trevaskis)""",female,29.00,0,2,29103,23.0000,NaN,S
89,981,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S
101,993,2,"Weisz, Mr. Leopold",male,27.00,1,0,228414,26.0000,NaN,S
120,1012,2,"Watt, Miss. Bertha J",female,12.00,0,0,C.A. 33595,15.7500,NaN,S
236,1128,1,"Warren, Mr. Frank Manley",male,64.00,1,0,110813,75.2500,D37,C
267,1159,3,"Warren, Mr. Charles William",male,NaN,0,0,C.A. 49867,7.5500,NaN,S
362,1254,2,"Ware, Mrs. John James (Florence Louise Long)",female,31.00,0,0,CA 31352,21.0000,NaN,S
406,1298,2,"Ware, Mr. William Jeffery",male,23.00,1,0,28666,10.5000,NaN,S
278,1170,2,"Ware, Mr. John James",male,30.00,1,0,CA 31352,21.0000,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
349,1241,2,"Walcroft, Miss. Nellie",female,31.00,0,0,F.C.C. 13528,21.0000,NaN,S
235,1127,3,"Vendel, Mr. Olof Edvin",male,20.00,0,0,350416,7.8542,NaN,S
189,1081,2,"Veal, Mr. James",male,40.00,0,0,28221,13.0000,NaN,S
311,1203,3,"Vartanian, Mr. David",male,22.00,0,0,2658,7.2250,NaN,C
145,1037,3,"Vander Planke, Mr. Julius",male,31.00,3,0,345763,18.0000,NaN,S
68,960,1,"Tucker, Mr. Gilbert Milligan Jr",male,31.00,0,0,2543,28.5375,C53,C
283,1175,3,"Touma, Miss. Maria Youssef",female,9.00,1,1,2650,15.2458,NaN,C
161,1053,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,NaN,C
173,1065,3,"Torfa, Mr. Assad",male,NaN,0,0,2673,7.2292,NaN,C
219,1111,3,"Thomson, Mr. Alexander Morrison",male,NaN,0,0,32302,8.0500,NaN,S
104,996,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16.00,1,1,2625,8.5167,NaN,C
332,1224,3,"Thomas, Mr. Tannous",male,NaN,0,0,2684,7.2250,NaN,C
116,1008,3,"Thomas, Mr. John",male,NaN,0,0,2681,6.4375,NaN,C
133,1025,3,"Thomas, Mr. Charles P",male,NaN,1,0,2621,6.4375,NaN,C
95,987,3,"Tenglin, Mr. Gunnar Isidor",male,25.00,0,0,350033,7.7958,NaN,S
230,1122,2,"Sweet, Mr. George Frederick",male,14.00,0,0,220845,65.0000,NaN,S

In [13]:
df.sort_index()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [14]:
df['Name'].sort_values().head()

392                Abbott, Master. Eugene Joseph
345                  Abelseth, Miss. Karen Marie
57                 Abelseth, Mr. Olaus Jorgensen
251     Abrahamsson, Mr. Abraham August Johannes
8      Abrahim, Mrs. Joseph (Sophie Halaut Easu)
Name: Name, dtype: object

In [15]:
df['Fare'].nlargest(10)

343    512.3292
53     263.0000
69     263.0000
24     262.3750
59     262.3750
64     262.3750
142    262.3750
375    262.3750
184    247.5208
202    227.5250
Name: Fare, dtype: float64

In [16]:
df.nlargest(10,'Fare')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
343,1235,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C
53,945,1,"Fortune, Miss. Ethel Flora",female,28.0,3,2,19950,263.0000,C23 C25 C27,S
69,961,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.0,1,4,19950,263.0000,C23 C25 C27,S
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
59,951,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C
64,956,1,"Ryerson, Master. John Borie",male,13.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
142,1034,1,"Ryerson, Mr. Arthur Larned",male,61.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
375,1267,1,"Bowen, Miss. Grace Scott",female,45.0,0,0,PC 17608,262.3750,NaN,C
184,1076,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.0,1,1,PC 17558,247.5208,B58 B60,C
202,1094,1,"Astor, Col. John Jacob",male,47.0,1,0,PC 17757,227.5250,C62 C64,C

In [18]:
df['Fare'].nsmallest(10)

266    0.0000
372    0.0000
21     3.1708
116    6.4375
133    6.4375
232    6.4958
291    6.9500
1      7.0000
163    7.0000
211    7.0500
Name: Fare, dtype: float64

In [19]:
df.nsmallest(10,'Fare')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
266,1158,1,"Chisholm, Mr. Roderick Robert Crispin",male,NaN,0,0,112051,0.0000,NaN,S
372,1264,1,"Ismay, Mr. Joseph Bruce",male,49.0,0,0,112058,0.0000,B52 B54 B56,S
21,913,3,"Olsen, Master. Artur Karl",male,9.0,0,1,C 17368,3.1708,NaN,S
116,1008,3,"Thomas, Mr. John",male,NaN,0,0,2681,6.4375,NaN,C
133,1025,3,"Thomas, Mr. Charles P",male,NaN,1,0,2621,6.4375,NaN,C
232,1124,3,"Wiklund, Mr. Karl Johan",male,21.0,1,0,3101266,6.4958,NaN,S
291,1183,3,"Daly, Miss. Margaret Marcella Maggie""""",female,30.0,0,0,382650,6.9500,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
163,1055,3,"Pearce, Mr. Ernest",male,NaN,0,0,343271,7.0000,NaN,S
211,1103,3,"Finoli, Mr. Luigi",male,NaN,0,0,SOTON/O.Q. 3101308,7.0500,NaN,S