In [1]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df = pd.read_csv('train.csv')

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
pivot1 = pd.pivot_table(df, values='Fare', index='Pclass')

In [7]:
pivot1

             Fare
Pclass
1       84.154687
2       20.662183
3       13.675550

In [8]:
pivot2 = pd.pivot_table(df, values='Fare', index='Pclass', columns='Sex', aggfunc='mean')

In [9]:
pivot2

Sex         female       male
Pclass
1       106.125798  67.226127
2        21.970121  19.741782
3        16.118810  12.661633

In [10]:
pivot2.reset_index()

Sex  Pclass      female       male
0         1  106.125798  67.226127
1         2   21.970121  19.741782
2         3   16.118810  12.661633

In [11]:
pivot3 = pd.pivot_table(df, values='Survived', index='Pclass', columns='Sex', aggfunc='mean')

In [12]:
pivot3

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [13]:
pivot4 = pd.pivot_table(df, values='PassengerId', index='Pclass', columns='Embarked', aggfunc='count')

In [14]:
pivot4

Embarked   C   Q    S
Pclass
1         85   2  127
2         17   3  164
3         66  72  353

In [15]:
pivot5 = pd.pivot_table(df, values='PassengerId', index='Pclass', aggfunc=['count','mean','sum'])

In [16]:
pivot5

             count        mean         sum
       PassengerId PassengerId PassengerId
Pclass
1              216  461.597222       99705
2              184  445.956522       82056
3              491  439.154786      215625

In [18]:
pivot6 = pd.pivot_table(df, values='Fare', index='Pclass', aggfunc=['count','mean','sum'],fill_value=0)

In [19]:
pivot6

       count       mean         sum
        Fare       Fare        Fare
Pclass
1        216  84.154687  18177.4125
2        184  20.662183   3801.8417
3        491  13.675550   6714.6951

In [20]:
pivot7 = pd.pivot_table(df, values='Fare', index=['Pclass','Cabin'], aggfunc=['count','mean','sum'],fill_value=0)

In [21]:
pivot7

             count      mean      sum
              Fare      Fare     Fare
Pclass Cabin
1      A10       1  40.12500  40.1250
       A14       1  52.00000  52.0000
       A16       1  39.60000  39.6000
       A19       1  26.00000  26.0000
       A20       1  56.92920  56.9292
...            ...       ...      ...
3      F E69     1  22.35830  22.3583
       F G63     1   7.65000   7.6500
       F G73     2   7.65000  15.3000
       F38       1   7.75000   7.7500
       G6        4  13.58125  54.3250

[147 rows x 3 columns]

In [24]:
pivot8 = pd.pivot_table(df, values='Fare', index='Pclass', aggfunc='sum', margins=True, margins_name='Total')

In [25]:
pivot8

              Fare
Pclass
1       18177.4125
2        3801.8417
3        6714.6951
Total   28693.9493

In [33]:
pivot9 = pd.pivot_table(df, values='Fare', index='Cabin',columns='Sex', aggfunc= lambda x:len(x))

In [34]:
pivot9

Sex    female  male
Cabin
A10       NaN   1.0
A14       NaN   1.0
A16       1.0   NaN
A19       NaN   1.0
A20       NaN   1.0
...       ...   ...
F33       3.0   NaN
F38       NaN   1.0
F4        1.0   1.0
G6        4.0   NaN
T         NaN   1.0

[147 rows x 2 columns]

In [35]:
pivot10 = pd.pivot_table(df, values='Fare', index='Cabin',columns='Sex', aggfunc= lambda x:len(x),fill_value=0)

In [36]:
pivot10

Sex    female  male
Cabin
A10         0     1
A14         0     1
A16         1     0
A19         0     1
A20         0     1
...       ...   ...
F33         3     0
F38         0     1
F4          1     1
G6          4     0
T           0     1

[147 rows x 2 columns]

In [39]:
pivot11 = pd.pivot_table(df, values=['Survived','Fare'], index='Cabin',columns='Sex', aggfunc = {'Survived':'sum','Fare':'mean'},fill_value=0)

In [40]:
pivot11

            Fare          Survived
Sex       female     male   female male
Cabin
A10     0.000000  40.1250        0    0
A14     0.000000  52.0000        0    0
A16    39.600000   0.0000        1    0
A19     0.000000  26.0000        0    0
A20     0.000000  56.9292        0    1
...          ...      ...      ...  ...
F33    11.333333   0.0000        3    0
F38     0.000000   7.7500        0    0
F4     39.000000  39.0000        1    1
G6     13.581250   0.0000        2    0
T       0.000000  35.5000        0    0

[147 rows x 4 columns]

In [41]:
pivot7.to_excel('Pivot_Table.xlsx') # to convert pivot7 to excel sheet